// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RomPilot.Core.Database;

#nullable disable

namespace RomPilot.Core.Migrations
{
    [DbContext(typeof(RomPilotDbContext))]
    [Migration("20251214162422_AddFilePathInArchiveToScannedFile")]
    partial class AddFilePathInArchiveToScannedFile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RomPilot.Core.Models.Checksum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScannedFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScannedFileId", "HashType");

                    b.HasIndex("ScannedFileId");

                    b.HasIndex("HashType", "HashValue");

                    b.ToTable("Checksums");
                });

            modelBuilder.Entity("RomPilot.Core.Models.Console", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportFormat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecalboxFolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RommPlatformId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportedFormats")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.ToTable("Consoles");
                });

            modelBuilder.Entity("RomPilot.Core.Models.DatabaseSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatfilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DatabaseSources");
                });

            modelBuilder.Entity("RomPilot.Core.Models.ExclusionFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilterType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilterValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("FilterType", "FilterValue");

                    b.ToTable("ExclusionFilters");
                });

            modelBuilder.Entity("RomPilot.Core.Models.ExportConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConflictResolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionTestError")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionTestStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormatRequirement")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastConnectionTest")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteDirectory")
                        .HasColumnType("TEXT");

                    b.Property<string>("SftpAuthMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("SftpHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("SftpKeyPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SftpPasswordEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<int>("SftpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SftpUsername")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExportConfigurations");
                });

            modelBuilder.Entity("RomPilot.Core.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelectedDatabaseSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectedScannedFileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsoleId");

                    b.HasIndex("SelectedDatabaseSourceId");

                    b.HasIndex("SelectedScannedFileId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("RomPilot.Core.Models.GameEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DatabaseSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityFlags")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReferenceDatabaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoFormat")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsoleId");

                    b.HasIndex("DatabaseSourceId");

                    b.HasIndex("ReferenceDatabaseId");

                    b.HasIndex("HashType", "HashValue");

                    b.ToTable("GameEntries");
                });

            modelBuilder.Entity("RomPilot.Core.Models.GameRomVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScannedFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectionScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasAlternateKey("GameId", "ScannedFileId");

                    b.HasIndex("GameEntryId");

                    b.HasIndex("GameId");

                    b.HasIndex("ScannedFileId");

                    b.ToTable("GameRomVersions");
                });

            modelBuilder.Entity("RomPilot.Core.Models.Metadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Developer")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreenshotPaths")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("RomPilot.Core.Models.ReferenceDatabase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Console")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DownloadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadStatus");

                    b.HasIndex("Provider", "Console", "Version")
                        .IsUnique();

                    b.ToTable("ReferenceDatabases");
                });

            modelBuilder.Entity("RomPilot.Core.Models.ScannedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchiveDepth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArchivePath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConsoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExclusionReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePathInArchive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdentificationStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastModifiedTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsoleId");

                    b.HasIndex("GameEntryId");

                    b.HasIndex("IdentificationStatus");

                    b.HasIndex("FilePath", "LastModifiedTimestamp");

                    b.ToTable("ScannedFiles");
                });

            modelBuilder.Entity("RomPilot.Core.Models.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimePlayed")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("UserRating")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.HasIndex("IsFavorite");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("RomPilot.Core.Models.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("RomPilot.Core.Models.Checksum", b =>
                {
                    b.HasOne("RomPilot.Core.Models.ScannedFile", "ScannedFile")
                        .WithMany("Checksums")
                        .HasForeignKey("ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("RomPilot.Core.Models.Game", b =>
                {
                    b.HasOne("RomPilot.Core.Models.Console", "Console")
                        .WithMany("Games")
                        .HasForeignKey("ConsoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RomPilot.Core.Models.DatabaseSource", "SelectedDatabaseSource")
                        .WithMany()
                        .HasForeignKey("SelectedDatabaseSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RomPilot.Core.Models.ScannedFile", "SelectedScannedFile")
                        .WithMany()
                        .HasForeignKey("SelectedScannedFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Console");

                    b.Navigation("SelectedDatabaseSource");

                    b.Navigation("SelectedScannedFile");
                });

            modelBuilder.Entity("RomPilot.Core.Models.GameEntry", b =>
                {
                    b.HasOne("RomPilot.Core.Models.Console", "Console")
                        .WithMany("GameEntries")
                        .HasForeignKey("ConsoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RomPilot.Core.Models.DatabaseSource", null)
                        .WithMany("GameEntries")
                        .HasForeignKey("DatabaseSourceId");

                    b.HasOne("RomPilot.Core.Models.ReferenceDatabase", "ReferenceDatabase")
                        .WithMany("GameEntries")
                        .HasForeignKey("ReferenceDatabaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Console");

                    b.Navigation("ReferenceDatabase");
                });

            modelBuilder.Entity("RomPilot.Core.Models.GameRomVersion", b =>
                {
                    b.HasOne("RomPilot.Core.Models.GameEntry", "GameEntry")
                        .WithMany("GameRomVersions")
                        .HasForeignKey("GameEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RomPilot.Core.Models.Game", "Game")
                        .WithMany("GameRomVersions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RomPilot.Core.Models.ScannedFile", "ScannedFile")
                        .WithMany("GameRomVersions")
                        .HasForeignKey("ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GameEntry");

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("RomPilot.Core.Models.Metadata", b =>
                {
                    b.HasOne("RomPilot.Core.Models.Game", "Game")
                        .WithMany("Metadata")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("RomPilot.Core.Models.ScannedFile", b =>
                {
                    b.HasOne("RomPilot.Core.Models.Console", "Console")
                        .WithMany("ScannedFiles")
                        .HasForeignKey("ConsoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RomPilot.Core.Models.GameEntry", "GameEntry")
                        .WithMany()
                        .HasForeignKey("GameEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Console");

                    b.Navigation("GameEntry");
                });

            modelBuilder.Entity("RomPilot.Core.Models.UserData", b =>
                {
                    b.HasOne("RomPilot.Core.Models.Game", "Game")
                        .WithOne("UserData")
                        .HasForeignKey("RomPilot.Core.Models.UserData", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("RomPilot.Core.Models.Console", b =>
                {
                    b.Navigation("GameEntries");

                    b.Navigation("Games");

                    b.Navigation("ScannedFiles");
                });

            modelBuilder.Entity("RomPilot.Core.Models.DatabaseSource", b =>
                {
                    b.Navigation("GameEntries");
                });

            modelBuilder.Entity("RomPilot.Core.Models.Game", b =>
                {
                    b.Navigation("GameRomVersions");

                    b.Navigation("Metadata");

                    b.Navigation("UserData");
                });

            modelBuilder.Entity("RomPilot.Core.Models.GameEntry", b =>
                {
                    b.Navigation("GameRomVersions");
                });

            modelBuilder.Entity("RomPilot.Core.Models.ReferenceDatabase", b =>
                {
                    b.Navigation("GameEntries");
                });

            modelBuilder.Entity("RomPilot.Core.Models.ScannedFile", b =>
                {
                    b.Navigation("Checksums");

                    b.Navigation("GameRomVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
