// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RomPilot.Core.Database;

#nullable disable

namespace RomPilot.Core.Migrations
{
    [DbContext(typeof(RomPilotDbContext))]
    partial class RomPilotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("RomPilot.Core.Models.Checksum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RomFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasAlternateKey("RomFileId", "HashType");

                    b.HasIndex("RomFileId");

                    b.HasIndex("HashType", "HashValue");

                    b.ToTable("Checksums");
                });

            modelBuilder.Entity("RomPilot.Core.Models.Console", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportFormat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecalboxFolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RommPlatformId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportedFormats")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.ToTable("Consoles");
                });

            modelBuilder.Entity("RomPilot.Core.Models.DatabaseSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatfilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DatabaseSources");
                });

            modelBuilder.Entity("RomPilot.Core.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelectedDatabaseSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectedRomFileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsoleId");

                    b.HasIndex("SelectedDatabaseSourceId");

                    b.HasIndex("SelectedRomFileId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("RomPilot.Core.Models.GameEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DatabaseSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityFlags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsoleId");

                    b.HasIndex("DatabaseSourceId");

                    b.HasIndex("HashType", "HashValue");

                    b.ToTable("GameEntries");
                });

            modelBuilder.Entity("RomPilot.Core.Models.GameRomVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RomFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectionScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasAlternateKey("GameId", "RomFileId");

                    b.HasIndex("GameEntryId");

                    b.HasIndex("GameId");

                    b.HasIndex("RomFileId");

                    b.ToTable("GameRomVersions");
                });

            modelBuilder.Entity("RomPilot.Core.Models.Metadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Developer")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreenshotPaths")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("RomPilot.Core.Models.RomFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchiveDepth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArchivePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsoleId");

                    b.ToTable("RomFiles");
                });

            modelBuilder.Entity("RomPilot.Core.Models.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimePlayed")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("UserRating")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.HasIndex("IsFavorite");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("RomPilot.Core.Models.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("RomPilot.Core.Models.Checksum", b =>
                {
                    b.HasOne("RomPilot.Core.Models.RomFile", "RomFile")
                        .WithMany("Checksums")
                        .HasForeignKey("RomFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RomFile");
                });

            modelBuilder.Entity("RomPilot.Core.Models.Game", b =>
                {
                    b.HasOne("RomPilot.Core.Models.Console", "Console")
                        .WithMany("Games")
                        .HasForeignKey("ConsoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RomPilot.Core.Models.DatabaseSource", "SelectedDatabaseSource")
                        .WithMany()
                        .HasForeignKey("SelectedDatabaseSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RomPilot.Core.Models.RomFile", "SelectedRomFile")
                        .WithMany()
                        .HasForeignKey("SelectedRomFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Console");

                    b.Navigation("SelectedDatabaseSource");

                    b.Navigation("SelectedRomFile");
                });

            modelBuilder.Entity("RomPilot.Core.Models.GameEntry", b =>
                {
                    b.HasOne("RomPilot.Core.Models.Console", "Console")
                        .WithMany("GameEntries")
                        .HasForeignKey("ConsoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RomPilot.Core.Models.DatabaseSource", "DatabaseSource")
                        .WithMany("GameEntries")
                        .HasForeignKey("DatabaseSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Console");

                    b.Navigation("DatabaseSource");
                });

            modelBuilder.Entity("RomPilot.Core.Models.GameRomVersion", b =>
                {
                    b.HasOne("RomPilot.Core.Models.GameEntry", "GameEntry")
                        .WithMany("GameRomVersions")
                        .HasForeignKey("GameEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RomPilot.Core.Models.Game", "Game")
                        .WithMany("GameRomVersions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RomPilot.Core.Models.RomFile", "RomFile")
                        .WithMany("GameRomVersions")
                        .HasForeignKey("RomFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GameEntry");

                    b.Navigation("RomFile");
                });

            modelBuilder.Entity("RomPilot.Core.Models.Metadata", b =>
                {
                    b.HasOne("RomPilot.Core.Models.Game", "Game")
                        .WithMany("Metadata")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("RomPilot.Core.Models.RomFile", b =>
                {
                    b.HasOne("RomPilot.Core.Models.Console", "Console")
                        .WithMany("RomFiles")
                        .HasForeignKey("ConsoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Console");
                });

            modelBuilder.Entity("RomPilot.Core.Models.UserData", b =>
                {
                    b.HasOne("RomPilot.Core.Models.Game", "Game")
                        .WithOne("UserData")
                        .HasForeignKey("RomPilot.Core.Models.UserData", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("RomPilot.Core.Models.Console", b =>
                {
                    b.Navigation("GameEntries");

                    b.Navigation("Games");

                    b.Navigation("RomFiles");
                });

            modelBuilder.Entity("RomPilot.Core.Models.DatabaseSource", b =>
                {
                    b.Navigation("GameEntries");
                });

            modelBuilder.Entity("RomPilot.Core.Models.Game", b =>
                {
                    b.Navigation("GameRomVersions");

                    b.Navigation("Metadata");

                    b.Navigation("UserData");
                });

            modelBuilder.Entity("RomPilot.Core.Models.GameEntry", b =>
                {
                    b.Navigation("GameRomVersions");
                });

            modelBuilder.Entity("RomPilot.Core.Models.RomFile", b =>
                {
                    b.Navigation("Checksums");

                    b.Navigation("GameRomVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
